site_name: Fetisch-Dating-Plattform
site_description: Diskrete, KI-gestützte Dating-Plattform für die Fetisch-Community
site_author: swisscomfort
site_url: https://swisscomfort.github.io/gnitad/
repo_url: https://github.com/swisscomfort/gnitad
repo_name: gnitad
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: purple
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Heller Modus
    - scheme: slate
      primary: purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Dunkler Modus

nav:
  - Startseite: index.md
  - API:
      - Endpoints: api/endpoints.md
  - Deployment:
      - Production Guide: deployment/production-guide.md
  - Development:
      - Quick Start: ../QUICKSTART.md
      - Contributing: ../CONTRIBUTING.md
  - GitHub: https://github.com/swisscomfort/gnitad

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/swisscomfort/gnitad
    - icon: fontawesome/solid/envelope
      link: mailto:contact@fetisch-dating.com
  version:
    provider: mike

copyright: "&copy; 2025 swisscomfort | MIT License"
